apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-dp
spec:
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: andremf/consumer
          env:
            - name: SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS
              value: kafka-svc:9092
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-svc
spec:
  type: NodePort
  selector:
    app: consumer
  ports:
    - port: 8081
      nodePort: 30001