apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-dp
spec:
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: andremf/producer
          env:
            - name: SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS
              value: kafka-svc:9092
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: producer-svc
spec:
  type: NodePort
  selector:
    app: producer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000